export const Users = [
  {
    picture: null,
    pangalan: "Darryl Javier",
    program: "Community",
    palayaw: "Darealtube",
    edad: "18-24",
    kasarian: "Lalaki",
    birthday: "September 6, 2004",
    yearAdmitted: "2018",
    relihiyon: "Christian",
    status: "Active",
    goal1Progress: 100,
    goal2Progress: 75,
    goal3Progress: 0,
    goal4Progress: 0,
    caseNo: 8591273056712,
  },
  {
    picture: null,
    pangalan: "Andrea Dulin",
    program: "Community",
    palayaw: "Ann",
    edad: "18-24",
    kasarian: "Babae",
    birthday: "February 3, 2004",
    yearAdmitted: "2019",
    relihiyon: "Roman Catholic",
    status: "Active",
    goal1Progress: 100,
    goal2Progress: 100,
    goal3Progress: 100,
    goal4Progress: 100,
    caseNo: 9604573285916,
  },
  {
    picture: null,
    pangalan: "Ralph Gabriel Bautista",
    program: "Home Care",
    palayaw: "Ralph",
    edad: "18-24",
    kasarian: "Lalaki",
    birthday: "",
    yearAdmitted: "2020",
    relihiyon: "",
    status: "Deleted",
    goal1Progress: 100,
    goal2Progress: 100,
    goal3Progress: 50,
    goal4Progress: 0,
    caseNo: 7694037691028,
  },
  {
    picture: null,
    pangalan: "Jaryll Francis Salvador",
    program: "Home Care",
    palayaw: "Jaryll",
    edad: "18-24",
    kasarian: "Lalaki",
    birthday: "",
    yearAdmitted: "2021",
    relihiyon: "",
    status: "Active",
    goal1Progress: 100,
    goal2Progress: 100,
    goal3Progress: 100,
    goal4Progress: 25,
    caseNo: 8564638501782,
  },
];
