export const Users = [
  {
    picture: null,
    pangalan: "Darryl Javier",
    program: "Community Based Program",
    palayaw: "Darealtube",
    edad: "19",
    kasarian: "Lalaki",
    birthday: "September 6, 2004",
    relihiyon: "Christian",
    goal1Progress: 100,
    goal2Progress: 75,
    goal3Progress: 0,
    goal4Progress: 0,
    caseNo: 8591273056712,
  },
  {
    picture: null,
    pangalan: "Andrea Dulin",
    program: "Community Based Program",
    palayaw: "Ann",
    edad: "19",
    kasarian: "Female",
    birthday: "February 3, 2004",
    relihiyon: "Roman Catholic",
    goal1Progress: 100,
    goal2Progress: 100,
    goal3Progress: 100,
    goal4Progress: 100,
    caseNo: 9604573285916,
  },
  {
    picture: null,
    pangalan: "Ralph Gabriel Bautista",
    program: "Home Care",
    palayaw: "Ralph",
    edad: "",
    kasarian: "Male",
    birthday: "",
    relihiyon: "",
    goal1Progress: 100,
    goal2Progress: 100,
    goal3Progress: 50,
    goal4Progress: 0,
    caseNo: 7694037691028,
  },
  {
    picture: null,
    pangalan: "Jaryll Francis Salvador",
    program: "Home Care",
    palayaw: "Jaryll",
    edad: "",
    kasarian: "Male",
    birthday: "",
    relihiyon: "",
    goal1Progress: 100,
    goal2Progress: 100,
    goal3Progress: 100,
    goal4Progress: 25,
    caseNo: 8564638501782,
  },
];
